define('ROOT_PATH',dirname(__FILE__));
require ROOT_PATH.'/init.php';
$r=array('https://snzdy.tmall.com/','583016369093','玩具','3');
$title='收纳';
$list=new Lists();
//$info=$list->_getpl($r);
//$info=$list->_getshopid($r);
//$info=$list->_getshops($r);
//$info=$list->_getprodoctinfo($r);
//$info=$list->_gettotalpl($r);
//$info=$list->_getkwshops($r);
//$info=$list->_getcategory($r);
//$info=$list->_getshopinfo($r);
//$info=$list->_getallshops($r);
//$info=$list->_shoptop($r);
//$info=$list->title_split($title);
//$info=$list->xialaci($title);
$info=$list->tblm($r);
print_r($info);
